### ISSUE TITLE
[Documentation]Add readme of Simon game

### ISSUE THREAD

**Issue by Nitesh-thapliyal** [Bauddhik-Geeks/Simon-Game#2]

**Comment by avinash-tiwari** [comment]
@Nitesh-thapliyal Would like to work on this, please assign.
Thanks.

**Comment by harikanani** [comment]
> @Nitesh-thapliyal Would like to work on this, please assign. Thanks.

Go Ahead @avinash-tiwari You are welcome to organization and discord server for the further queries Happy Hacking!.😊
Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech

**Comment by prathamesh-borse** [comment]
@avinash-tiwari Are u working on this issue or I would like to take this issue.!

**Comment by avinash-tiwari** [comment]
@prathamesh-borse  this is done. @Nitesh-thapliyal can you close this issue? And all other open-done issues too?
Thanks.

**Comment by prathamesh-borse** [comment]
OK, @avinash-tiwari Thanks for the confirmation.

**Comment by Nitesh-thapliyal** [comment]
@prathamesh-borse you can check out other repos 😊
